#!/usr/bin/env bash

xdotool key super+e
#xdotool key super+1
xdotool key super+3
xdotool key super+space
sleep .25
source /home/hakirot/skps/spawns
xdotool key super+2
xdotool key super+w
xdotool key super+BackSpace
sleep .25
xdotool type "firefox"
sleep .25
xdotool key KP_Enter
sleep 1.5
xdotool key KP_Enter
sleep 1
xdotool key super+1
xdotool key super+c
