#!/usr/bin/env bash

xdotool key super+e
xdotool key super+1
xdotool key super+space
xdotool key super+3
source /home/hakirot/skps/spawns
xdotool key super+2
xdotool key super+w
xdotool key super+BackSpace
xdotool type "firefox"
xdotool key KP_Enter
sleep 3
xdotool key KP_Enter
