#!/bin/bash
# install tree
# install inotifytools

#notify="inotifywait @./node_modules -r -e close_write -e access -e delete . &> /dev/null"
notify="inotifywait @./node_modules -r -e close_write -e access . &> /dev/null"
cmd="git diff HEAD"

function run {
	clear
$cmd
}

run

while eval "$notify"; do
    run
done
