#!/bin/bash
# install tree
# install inotifytools

notify="inotifywait -r -e close_write . &> /dev/null"
cmd="make"

function run {
  echo "Starting build.."
  sleep 1
  clear
  date +%I:%M
  $cmd
}

run

while eval "$notify"; do
  run
  sleep 4
done
