#!/bin/bash
# install tree
# install inotifytools

notify="inotifywait -r -e close_write . &> /dev/null"
cmd="make"

function run {
  make clean
  clear
  date +%I:%M
  $cmd
  if [ $? -eq 0 ]
  then
    sleep 1
    echo Built.
  else
    echo Error.
  fi
}

run

while eval "$notify"; do
  run
  sleep 4
done
