#!/usr/bin/env bash

if [[ $# -eq 1 && $1 == "-d" ]]; then
  xdotool type "cd $PWD"
  xdotool key KP_Enter 
  xdotool type "gdv; SARA"
  xdotool key KP_Enter 
  xdotool key asterisk
  xdotool type "gg"
elif [[ $# -eq 1 && $1 == "-l" ]]; then
  xdotool type "cd $PWD"
  xdotool key KP_Enter 
  xdotool type "git log | v; SARA"
  xdotool key KP_Enter 
fi
