#!/bin/bash
# Dependencies
#   tree
#   inotifytools
#   bat

notify="inotifywait @./node_modules -r -e close_write -e access . &> /dev/null"
cmd="git status -s"
cmd3="bat --paging=never \
  --wrap=never \
  -d"

function run {

  clear
  sleep .15

  if [ -z "$($cmd)" ]
  then
    count=0
    while IFS= read -r line
    do
      if (( count == 0 ))
      then
        echo $line
      fi
      if (( count == 1 ))
      then
        re='^[0-9]+$'
        if ! [[ ${line:41} =~ $re ]]
        then
          echo "Up to date."
        else
          echo "${line:41}"
        fi
      fi
      count=$((count+1))
    done < <(git status)
  else
    echo " ------"
    $cmd
    echo " ------"

    while IFS= read -r line
    do
      if ! [ -z "$($cmd3 ${line:3})" ]
      then
        echo "${line:3}"
        eval "$cmd3 ${line:3}"
      fi
    done < <($cmd)
  fi
}


run

while eval "$notify"; do
    run
done
