#!/bin/bash
# Dependencies
#   tree
#   inotifytools
#   bat

notify="inotifywait @./node_modules -r -e close_write -e access . &> /dev/null"
cmd="git status -s"
cmd2="git --no-pager diff HEAD | \
  bat \
  --paging=never \
  -n"

cmd3="bat --paging=never \
  --wrap=never \
  -d \
  -p"

function run {
	clear
  sleep .13
#  eval "$cmd"
#  eval "$cmd2"

#  eval "$cmd"
  files=`git status -s`
#  eval "$cmd3 ${files:3}"

  echo " ------"
  $cmd
  echo " ------"
  while IFS= read -r line
  do
    echo "${line:3}"
    eval "$cmd3 ${line:3}"
  done < <($cmd)

}


run

while eval "$notify"; do
    run
done
