#!/bin/sh

set -eou pipefail

WALLS_DIR=/home/hakirot/pix/wall


# LOAD SAVE
#wall=city
#wall=clearing
#wall=futurepunk
#wall=newyorknight (could use edit)
#wall=rocket
#wall=sunset
#wall=farfaraway
#wall=timberland
#wall=mountains

# Prioritize command-line arg
if  [[ $# -eq 1 ]]; then
  wall=$1
# If no save, randomize
elif [ -z ${wall+x} ]; then
  wall=$(find ~/pix/wall/ | shuf -n 1)
# Else execute save
else
  wall=$WALLS_DIR/$wall
fi

# Add this as background wallpaper
xwallpaper --zoom $wall

# Clear
wal -c

# Generate color scheme 
if [[ $wall =~ "clearing" ]]; then
  wal --theme custom-clearing
elif [[ $wall =~ "city" ]]; then
  wal --theme custom-city
elif [[ $wall =~ "futurepunk" ]]; then
  wal --theme custom-futurepunk
elif [[ $wall =~ "newyorknight" ]]; then
  wal --theme custom-newyorknight
elif [[ $wall =~ "rocket" ]]; then
  wal --theme custom-rocket
elif [[ $wall =~ "farfaraway" ]]; then
  wal --theme custom-farfaraway
elif [[ $wall =~ "sunset" ]]; then
  wal --theme custom-sunset
elif [[ $wall =~ "timberland" ]]; then
  wal --theme custom-timberland
elif [[ $wall =~ "mountains" ]]; then
  wal --theme custom-mountains
else
  wal -i $wall
fi

xdotool key super+F5
