#!/bin/sh

set -eou pipefail

WALLS_DIR=/home/hakirot/pix/wall

# LOAD SAVE
#wall=koi

# Prioritize command-line arg
if  [[ $# -eq 1 ]]; then
  wall=$1
# If no save, randomize
elif [ -z ${wall+x} ]; then
  wall=$(find ~/pix/wall/ | shuf -n 1)
# Else execute save
else
  wall=$WALLS_DIR/$wall
fi

# Add this as background wallpaper
xwallpaper --zoom $wall

# Clear
wal -c

# Generate color scheme 
if [[ $wall =~ "clearing" ]]; then
  wal -a 92 --theme custom-clearing
elif [[ $wall =~ "city" ]]; then
  wal -a 92 --theme custom-city
elif [[ $wall =~ "futurepunk" ]]; then
  wal -a 92 --theme custom-futurepunk
elif [[ $wall =~ "rocket" ]]; then
  wal -a 92 --theme custom-rocket
elif [[ $wall =~ "farfaraway" ]]; then
  wal -a 92 --theme custom-farfaraway
elif [[ $wall =~ "timberland" ]]; then
  wal -a 92 --theme custom-timberland
elif [[ $wall =~ "mountains1" ]]; then
  wal -a 92 --theme custom-mountains
elif [[ $wall =~ "alpine3" ]]; then
  wal -a 92 --theme custom-alpine3
elif [[ $wall =~ "keebz" ]]; then
  wal -a 92 --theme custom-keebz
elif [[ $wall =~ "drgn" ]]; then
  wal -a 92 --theme custom-drgn
elif [[ $wall =~ "bladerunner" ]]; then
  wal -a 92 --theme custom-bladerunner
elif [[ $wall =~ "kohakunushi" ]]; then
  wal -a 92 --theme custom-kohakunushi
elif [[ $wall =~ "dystopia" ]]; then
# wal -a 92 --theme custom-tomorrownightburns
  wal -a 92 --theme custom-dystopia
elif [[ $wall =~ "graffiti" ]]; then
  wal -a 92 --theme custom-graffiti
elif [[ $wall =~ "road_through_desert" ]]; then
  wal -a 92 --theme custom-road-through-desert
elif [[ $wall =~ "koi" ]]; then
  wal -a 92 --theme custom-koi
elif [[ $wall =~ "breathe" ]]; then
  wal -a 92 --theme custom-breathe
elif [[ $wall =~ "orbits" ]]; then
  wal -a 92 --theme custom-orbits
else
  wal -a 92 -i $wall
fi

# For vanilla dwm
#xdotool key super+F5

#source /home/hakirot/.config/polybar/bar.sh

killall polybar
sleep 1;
MONITOR=eDP-1 polybar center --config=$HOME/.config/polybar/config.ini &
MONITOR=HDMI-1 polybar secondary-center --config=$HOME/.config/polybar/config.ini &
