#!/usr/bin/env bash

sleep .25
xdotool key super+space
sleep .5
xdotool key M
xdotool key KP_Enter
xdotool key KP_Enter

xdotool key control+j
xdotool key c

sleep .25
xdotool key q
xdotool type "startproxy"
xdotool key KP_Enter
sleep .5
xdotool type "asdf"
xdotool key KP_Enter

xdotool key control+j
xdotool key c

xdotool key R

sleep .25
xdotool key alt+1
sleep .25
xdotool key 2
sleep .25
xdotool key l
sleep .25
xdotool key l
sleep .25
xdotool key 1
for i in {1..6}; do
  xdotool key alt+z
done
