#!/usr/bin/env bash

#sleep .25
#xdotool key super+space
#sleep .5
xdotool key alt+minus
xdotool key M
xdotool key KP_Enter
xdotool key KP_Enter

xdotool key control+j
xdotool key c

sleep .25
xdotool key q
xdotool type "startproxy"
xdotool key KP_Enter
sleep 1
xdotool type "asdf"
xdotool key KP_Enter

sleep .25
xdotool key alt+minus
xdotool key q
xdotool type "proxy2"
xdotool key KP_Enter
sleep 1
xdotool type "gabagool"
xdotool key KP_Enter

xdotool key control+j
xdotool key c

xdotool key R

sleep .25
xdotool key alt+1
sleep .25
xdotool key 2
sleep .25
xdotool key j
sleep .25
xdotool key j

xdotool key alt+j
xdotool key Q

# blink
xdotool key alt+x
xdotool key alt+x
xdotool key alt+z
xdotool key alt+z
xdotool key alt+x
xdotool key alt+x
xdotool key alt+z
xdotool key alt+z
