#!/usr/bin/env bash

# Get list of WiFi networks
networks=$(nmcli -t -f SSID dev wifi list | sort -u)

selected=$(echo "$networks" | dmenu)

# Connect to selected network
if [ -n "$selected" ]; then
  xdotool key super+e
  xdotool key super+space
  xdotool key Q
  sleep .1
  xdotool key control+l
  sleep .2
  xdotool type "nmcli device wifi connect ${selected} --ask"
  xdotool key KP_Enter
fi
